{"uid":"7ebb99389525b85a","name":"test_save_as_reference_imageFile","fullName":"tests.test_previewApp_ImageComparison.TestImageComparisonSaveAs#test_save_as_reference_imageFile","historyId":"ed4d5dc6ed995754c7759c6c3702c9e5","time":{"start":1729916430617,"stop":1729916440390,"duration":9773},"description":"Save the opened image as a reference image.","descriptionHtml":"<p>Save the opened image as a reference image.</p>\n","status":"broken","statusMessage":"FileNotFoundError: Error: The file '/Users/runner/work/gui-chaos-pytest/gui-chaos-pytest/fixtures/sourceImages/REF_Image.png' was not found.","statusTrace":"self = <test_previewApp_ImageComparison.TestImageComparisonSaveAs object at 0x1078db6f0>\nbaseDir = '/Users/runner/work/gui-chaos-pytest/gui-chaos-pytest'\n\n    @allure.step(\"Save the opened image as Reference Image\")\n    def test_save_as_reference_imageFile(self, baseDir):\n        \"\"\"Save the opened image as a reference image.\"\"\"\n    \n        file_path = os.path.join(baseDir, FIXTURES, SOURCE_IMAGES, REF_FILE_NAME)\n    \n        PreviewAppFunct.saveAsImage(REF_FILE_NAME)\n    \n        # ASSERT SAVE AS IMAGE IS EXIST\n>       PreviewAppFunct.assertcheckFileExists(file_path)\n\ntests/test_previewApp_ImageComparison.py:47: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nfilepath = '/Users/runner/work/gui-chaos-pytest/gui-chaos-pytest/fixtures/sourceImages/REF_Image.png'\n\n    @staticmethod\n    def assertcheckFileExists(filepath):\n        \"\"\"Check if the specified file exists and raise an exception if not.\"\"\"\n        if not os.path.isfile(filepath):\n>           raise FileNotFoundError(f\"Error: The file '{filepath}' was not found.\")\nE           FileNotFoundError: Error: The file '/Users/runner/work/gui-chaos-pytest/gui-chaos-pytest/fixtures/sourceImages/REF_Image.png' was not found.\n\nglobals/functions/previewApp.py:117: FileNotFoundError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"test_tearDown","time":{"start":1729916407963,"stop":1729916407963,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":false},{"name":"baseDir","time":{"start":1729916430616,"stop":1729916430616,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":false}],"testStage":{"description":"Save the opened image as a reference image.","status":"broken","statusMessage":"FileNotFoundError: Error: The file '/Users/runner/work/gui-chaos-pytest/gui-chaos-pytest/fixtures/sourceImages/REF_Image.png' was not found.","statusTrace":"self = <test_previewApp_ImageComparison.TestImageComparisonSaveAs object at 0x1078db6f0>\nbaseDir = '/Users/runner/work/gui-chaos-pytest/gui-chaos-pytest'\n\n    @allure.step(\"Save the opened image as Reference Image\")\n    def test_save_as_reference_imageFile(self, baseDir):\n        \"\"\"Save the opened image as a reference image.\"\"\"\n    \n        file_path = os.path.join(baseDir, FIXTURES, SOURCE_IMAGES, REF_FILE_NAME)\n    \n        PreviewAppFunct.saveAsImage(REF_FILE_NAME)\n    \n        # ASSERT SAVE AS IMAGE IS EXIST\n>       PreviewAppFunct.assertcheckFileExists(file_path)\n\ntests/test_previewApp_ImageComparison.py:47: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nfilepath = '/Users/runner/work/gui-chaos-pytest/gui-chaos-pytest/fixtures/sourceImages/REF_Image.png'\n\n    @staticmethod\n    def assertcheckFileExists(filepath):\n        \"\"\"Check if the specified file exists and raise an exception if not.\"\"\"\n        if not os.path.isfile(filepath):\n>           raise FileNotFoundError(f\"Error: The file '{filepath}' was not found.\")\nE           FileNotFoundError: Error: The file '/Users/runner/work/gui-chaos-pytest/gui-chaos-pytest/fixtures/sourceImages/REF_Image.png' was not found.\n\nglobals/functions/previewApp.py:117: FileNotFoundError","steps":[{"name":"Save the opened image as Reference Image","time":{"start":1729916430617,"stop":1729916440357,"duration":9740},"status":"broken","statusMessage":"FileNotFoundError: Error: The file '/Users/runner/work/gui-chaos-pytest/gui-chaos-pytest/fixtures/sourceImages/REF_Image.png' was not found.\n","statusTrace":"  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/Users/runner/work/gui-chaos-pytest/gui-chaos-pytest/tests/test_previewApp_ImageComparison.py\", line 47, in test_save_as_reference_imageFile\n    PreviewAppFunct.assertcheckFileExists(file_path)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"/Users/runner/work/gui-chaos-pytest/gui-chaos-pytest/globals/functions/previewApp.py\", line 117, in assertcheckFileExists\n    raise FileNotFoundError(f\"Error: The file '{filepath}' was not found.\")\n","steps":[],"attachments":[],"parameters":[{"name":"baseDir","value":"'/Users/runner/work/gui-chaos-pytest/gui-chaos-pytest'"}],"shouldDisplayMessage":true,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":true}],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"attachmentsCount":0,"attachmentStep":false,"stepsCount":1,"hasContent":true},"afterStages":[{"name":"test_tearDown::0","time":{"start":1729916487286,"stop":1729916489507,"duration":2221},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":false}],"labels":[{"name":"suite","value":"Image Comparison Test with Preview App by SAVE AS Method"},{"name":"parentSuite","value":"tests"},{"name":"subSuite","value":"TestImageComparisonSaveAs"},{"name":"host","value":"Mac-1729914925701.local"},{"name":"thread","value":"3939-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_previewApp_ImageComparison"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"7ebb99389525b85a.json","parameterValues":[]}